ci:
  autofix_prs: true
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  skip: [ty]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit

    rev: v0.15.11
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false
