services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    # Ограничиваем доступ к Qdrant извне, если не нужно
    # ports:
    #   - "127.0.0.1:6333:6333"
    networks:
      - homelab-net
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    image: ghcr.io/arassypnov/search-ui:latest
    user: "${UID:-1000}:${GID:-1000}"
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - homelab-net
    environment:
      - HF_HOME=/srv/search-ui/models_cache
    env_file: .env
    depends_on:
      qdrant:
        condition: service_started
    volumes:
      # Только данные, код уже внутри контейнера
      - ./downloads:/srv/search-ui/downloads
      - ./data:/srv/search-ui/data
      - ./storage:/srv/search-ui/storage
      - ./models_cache:/srv/search-ui/models_cache
      - ./config:/srv/search-ui/config

volumes:
  qdrant_data:

networks:
  homelab-net:
    external: true
